version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: 'monthly'
    groups:
      all-actions:
        patterns: [ "*" ]
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
        npm-prod-patch:
          dependency-type: "production"
          update-types: ["patch"]
        npm-prod-minor:
          dependency-type: "production"
          update-types: ["minor"]
        npm-prod-others:
          dependency-type: "production"
        npm-dev-patch:
          dependency-type: "development"
          update-types: ["patch"]
        npm-dev-minor:
          dependency-type: "development"
          update-types: ["minor"]
        npm-dev-others:
          dependency-type: "development"

