name: 'Index packages versions checker'
branding:
  icon: 'package'
  color: 'orange'
description: |
  In case lock file is updated, action will output versions differences as comment
inputs:
  gh-token:
    required: true
    description: |
      Github token used to fetch data from github API.
      See Readme for minimal permission requirements
  manager:
    required: true
    description: 'Which package manager to assess (Available: \"composer\")'
  post-results:
    required: true
    description: "Whether to post results as comment (\"true\" | \"false\")"
    default: "true"
  force:
    required: false
    description: "Force assessment even if no change occurred since last comment (Useful only for PRs and mostly if you need to rely on action output)"
    default: "false"
outputs:
  diff:
    description: "List of packages with version differences. See PackageVersionDiff type for more information"
runs:
  using: 'node12'
  pre: 'bin/configure.js'
  main: 'dist/index.js'
