name: 'CI'
on: # rebuild any PRs and main branch changes
  pull_request:
    types: [ synchronize ]
  push:
    branches: [ master ]

concurrency:
  group: "CI-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  ci-tests:
    name: "CI tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install"
        run: yarn install
      - name: "Compile"
        run: npm run compile
      - name: "Detect forgotten compilation before push"
        run: test -z "$(git diff --name-only dist/)"
      - name: "Lint"
        run: npm run lint
