name: 'CI'
on: # rebuild any PRs and main branch changes
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches: [ master ]

concurrency:
  group: "CI-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  ci-tests:
    name: "CI tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Retrieve node version for the action
        id: node_version
        run: |
          make get-action-nodejs-version
          echo "::set-output name=version::$(make get-action-nodejs-version)"
      - name: Configure NodeJs version
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.node_version.outputs.version }}'
      - name: "Build"
        run: make build
      - name: "Detect forgotten compilation before push"
        run: test -z "$(git diff --name-only dist/)"
      - name: "Lint"
        run: make lint
