name: 'CI'
on: # rebuild any PRs and main branch changes
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches: [ master ]

concurrency:
  group: "CI-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  ci-tests:
    env:
      NVM_DIR: ~/.nvm
    name: "CI tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Set the correct Node version using nvm
        shell: bash -l {0} 
        run: nvm install
      - name: "Build"
        run: source $NVM_DIR/nvm.sh && make build
      - name: "Detect forgotten compilation before push"
        run: test -z "$(git diff --name-only dist/)"
      - name: "Lint"
        run: make lint
