name: 'github-action-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: node bin/configure.js # Mandatory as `pre` execution is not supported for local action
      - uses: ./
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          manager: composer
