name: 'github-action-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install"
        run: yorn install
      - name: "Compile"
        run: npm run compile
      - name: "Lint"
        run: npm run lint
